// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUNCwUIdg52Gq7AZYZSLRv1ziiWjQfs7Y',
    appId: '1:479346789912:web:6401a47636c4fdd5ecfd6d',
    messagingSenderId: '479346789912',
    projectId: 'mis-lab-3-38361',
    authDomain: 'mis-lab-3-38361.firebaseapp.com',
    storageBucket: 'mis-lab-3-38361.firebasestorage.app',
    measurementId: 'G-HNEYEE6VJE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOluwQpdwlZ1MuDKxH_sOvm_AMTCm6mGA',
    appId: '1:479346789912:android:8e5d6d430a175f36ecfd6d',
    messagingSenderId: '479346789912',
    projectId: 'mis-lab-3-38361',
    storageBucket: 'mis-lab-3-38361.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbjyTUHunDD6E7zg2Zv9dJTYwUnPPQl2g',
    appId: '1:479346789912:ios:1aad8bae493a9e43ecfd6d',
    messagingSenderId: '479346789912',
    projectId: 'mis-lab-3-38361',
    storageBucket: 'mis-lab-3-38361.firebasestorage.app',
    iosBundleId: 'com.example.labZadaca2',
  );

}